class Employee { }
console.log(new Employee())
console.log(new Employee())
console.log(new Employee())
console.log(new Employee())
console.log(new Employee())
console.log(new Employee())
console.log(new Employee())
console.log(new Employee())
console.log(new Employee())
console.log(new Employee())
console.log(new Employee())
console.log(new Employee())
console.log(new Employee())
console.log(new Employee())