let employees = [{ "id": 1, "name": "Mandel", "email": "mlardnar0@sciencedirect.com", "gender": "Male" },
{ "id": 2, "name": "Wilie", "email": "wpetrol1@google.ru", "gender": "Female" },
{ "id": 3, "name": "Cosimo", "email": "ckibbel2@youku.com", "gender": "Male" },
{ "id": 4, "name": "Edith", "email": "efranses3@sogou.com", "gender": "Female" },
{ "id": 5, "name": "Lavina", "email": "lmerredy4@icq.com", "gender": "Female" },
{ "id": 6, "name": "Matilde", "email": "mpossel5@samsung.com", "gender": "Genderqueer" },
{ "id": 7, "name": "Wilfrid", "email": "wwinfred6@freewebs.com", "gender": "Male" },
{ "id": 8, "name": "Reagen", "email": "rlarby7@china.com.cn", "gender": "Male" },
{ "id": 9, "name": "Othello", "email": "oyurenev8@shareasale.com", "gender": "Male" },
{ "id": 10, "name": "Ruttger", "email": "rkreuzer9@moonfruit.com", "gender": "Male" },
{ "id": 11, "name": "Taite", "email": "tbeardsdalea@unc.edu", "gender": "Male" },
{ "id": 12, "name": "Martino", "email": "mhutchinsonb@symantec.com", "gender": "Male" },
{ "id": 13, "name": "Elwood", "email": "eharmc@symantec.com", "gender": "Male" },
{ "id": 14, "name": "Agnesse", "email": "asegged@washingtonpost.com", "gender": "Female" },
{ "id": 15, "name": "Daveen", "email": "dhuee@oracle.com", "gender": "Female" },
{ "id": 16, "name": "Elvira", "email": "eballintimef@bizjournals.com", "gender": "Female" },
{ "id": 17, "name": "Gardner", "email": "gpersentg@accuweather.com", "gender": "Male" },
{ "id": 18, "name": "Andromache", "email": "abotemanh@shinystat.com", "gender": "Female" },
{ "id": 19, "name": "Edith", "email": "edillistoni@xing.com", "gender": "Polygender" },
{ "id": 20, "name": "Berny", "email": "bdeetlefsj@unblog.fr", "gender": "Female" },
{ "id": 21, "name": "Aylmar", "email": "agentschk@google.fr", "gender": "Male" },
{ "id": 22, "name": "Joell", "email": "jgateleyl@vk.com", "gender": "Female" },
{ "id": 23, "name": "Daryn", "email": "dgydem@auda.org.au", "gender": "Female" },
{ "id": 24, "name": "Conni", "email": "cfilsonn@hostgator.com", "gender": "Female" },
{ "id": 25, "name": "Buffy", "email": "bredmondo@fda.gov", "gender": "Female" },
{ "id": 26, "name": "Ferris", "email": "fcullefordp@wisc.edu", "gender": "Male" },
{ "id": 27, "name": "Gibbie", "email": "gorthq@homestead.com", "gender": "Male" },
{ "id": 28, "name": "Calv", "email": "cfeltenr@uiuc.edu", "gender": "Male" },
{ "id": 29, "name": "Sibby", "email": "shambeltons@earthlink.net", "gender": "Non-binary" },
{ "id": 30, "name": "Allissa", "email": "amorlt@bbb.org", "gender": "Female" },
{ "id": 31, "name": "Susette", "email": "sdonatiu@opensource.org", "gender": "Female" },
{ "id": 32, "name": "Andris", "email": "alindermannv@msn.com", "gender": "Male" },
{ "id": 33, "name": "Ardyth", "email": "ahalsallw@msn.com", "gender": "Bigender" },
{ "id": 34, "name": "Emiline", "email": "elearmonthx@prlog.org", "gender": "Female" },
{ "id": 35, "name": "Philly", "email": "porringy@mayoclinic.com", "gender": "Female" },
{ "id": 36, "name": "Humfrid", "email": "hbenfieldz@usa.gov", "gender": "Male" },
{ "id": 37, "name": "Matilda", "email": "mshulem10@opensource.org", "gender": "Female" },
{ "id": 38, "name": "Helga", "email": "hcampbelldunlop11@hubpages.com", "gender": "Female" },
{ "id": 39, "name": "Irvine", "email": "isimmance12@zdnet.com", "gender": "Male" },
{ "id": 40, "name": "Maxie", "email": "mcarillo13@nature.com", "gender": "Male" },
{ "id": 41, "name": "Rosemary", "email": "rdobsons14@blogspot.com", "gender": "Female" },
{ "id": 42, "name": "Urson", "email": "ugoodbarr15@businessweek.com", "gender": "Male" },
{ "id": 43, "name": "Heloise", "email": "hleitche16@dropbox.com", "gender": "Female" },
{ "id": 44, "name": "Jenny", "email": "jwanley17@fda.gov", "gender": "Female" },
{ "id": 45, "name": "Ailina", "email": "anormanvell18@dropbox.com", "gender": "Female" },
{ "id": 46, "name": "Carol-jean", "email": "cliddicoat19@abc.net.au", "gender": "Female" },
{ "id": 47, "name": "Carmelita", "email": "ctruce1a@google.pl", "gender": "Genderfluid" },
{ "id": 48, "name": "Solly", "email": "sstrewther1b@berkeley.edu", "gender": "Male" },
{ "id": 49, "name": "Modestine", "email": "mpyvis1c@nhs.uk", "gender": "Female" },
{ "id": 50, "name": "Melisande", "email": "mdungey1d@prlog.org", "gender": "Female" }]

export default employees

//babel traspiler - presetting the env 
//import and export - keywords